### ISSUE TITLE
追加［魔法］：シルバーバレット

### ISSUE THREAD

**Issue by Hukino** [SALUNAinMC/SkyTraveller-datapack#24]
### 概要
- 敵を貫通する魔法弾を前方に射出する。

### 性能
- クールダウン 3sec
- 消費MP 15
-  ダメージ 10

### タスク
- [x] 魔法のアイテムテクスチャを追加
- [x] 弾のテクスチャ/モデルを作成
- [ ] アイテムの表示・情報を作成
- [ ] 本効果を作成

**Comment by zinn6118** [comment]
やるかも

**Comment by zinn6118** [comment]
![image](https://user-images.githubusercontent.com/69614928/160618041-8d683ff5-2fe7-4d84-834b-afcd0fb0de37.png)
[silver_bullet.zip](https://github.com/Hukino/Sky-traveller/files/8371627/silver_bullet.zip)
![silver_bullet](https://user-images.githubusercontent.com/69614928/160618134-f9c6c7a3-ff07-4daf-a296-37771e9cc0e7.png)
