### ISSUE TITLE
追加［武器］：昇月の魔剣

### ISSUE THREAD

**Issue by zinn6118** [SALUNAinMC/SkyTraveller-datapack#41]
### 概要
- 長剣武器
- 右クリックでMPを消費し、最大HPの半分のダメージを受けるが、一定時間武器の攻撃力が2.5倍になる

### 性能
- 攻撃力 14
- 攻撃速度 1.4

### タスク
- [x] モデル制作
- [x] 効果制作

**Comment by zinn6118** [comment]
モデルを制作してもよろしいでしょうか

**Comment by Hukino** [comment]
了解だよ

**Comment by zinn6118** [comment]
![image](https://user-images.githubusercontent.com/69614928/151702510-86a49b8a-6e05-4281-beea-b84d1b5f9abc.png)
[syougetu.zip](https://github.com/Hukino/Sky-traveller/files/7966021/syougetu.zip)

**Comment by Hukino** [comment]
ちょい修正とか加えるかもです

**Comment by zinn6118** [comment]
![image](https://user-images.githubusercontent.com/69614928/152116922-3dda4108-5064-411f-8f56-0274f51c5794.png)
[syougetu.zip](https://github.com/Hukino/Sky-traveller/files/7984644/syougetu.zip)

昨晩思いついたやつです

**Comment by Hukino** [comment]
できてた
