### ISSUE TITLE
追加［武器］：十字架の処刑剣

### ISSUE THREAD

**Issue by zinn6118** [SALUNAinMC/SkyTraveller-datapack#45]
### 概要
- 斧武器
- 刀身の上部に十字架を思わせる飛び出た刃が付く処刑剣
- 右クリックで目の前の敵に雑魚なら即死するほどの大ダメージ(クールタイム60秒

### 性能
- 攻撃力 28
- 攻撃速度 0.6

### タスク
- [x] モデル制作
- [x] 効果制作

**Comment by zinn6118** [comment]
作るかもしれません

**Comment by zinn6118** [comment]
[cross_execution_sword.zip](https://github.com/Hukino/Sky-traveller/files/8238988/cross_execution_sword.zip)
![image](https://user-images.githubusercontent.com/69614928/158045811-13cf01b7-471b-469d-8191-98bd426cd2fd.png)
現状です

**Comment by zinn6118** [comment]
[cross_execution_sword修正版.zip](https://github.com/Hukino/Sky-traveller/files/8238989/cross_execution_sword.zip)
表示の設定漏れがあったので修正しました

**Comment by zinn6118** [comment]
![image](https://user-images.githubusercontent.com/69614928/160276633-d27a4818-4d19-4f5d-b59e-5b318b2ca654.png)
[cross_execution_sword2.zip](https://github.com/Hukino/Sky-traveller/files/8357326/cross_execution_sword2.zip)

**Comment by zinn6118** [comment]
![image](https://user-images.githubusercontent.com/69614928/160276698-a3261343-0402-435a-920e-b323e3b1abcd.png)
[cross_execution_sword2.zip](https://github.com/Hukino/Sky-traveller/files/8357331/cross_execution_sword2.zip)

**Comment by Hukino** [comment]
いいね！

**Comment by Hukino** [comment]
既に完成してた
