### ISSUE TITLE
追加［アイテム］：Beast Pain Maze

### ISSUE THREAD

**Issue by zinn6118** [SALUNAinMC/SkyTraveller-datapack#58]
### 概要
- ラジカセの形をした爆弾
- 音で周囲を攻撃

### タスク
- [x] アイテムの見た目を作成
- [x] 効果を作成

**Comment by Hukino** [comment]
![image](https://user-images.githubusercontent.com/79348353/171994037-ed5ed0bc-a69c-4ee6-92f1-4689a4b666f0.png)
描きました

**Comment by Hukino** [comment]
![image](https://user-images.githubusercontent.com/79348353/172042071-142508d0-1d6f-4786-ae22-ec94583af4f6.png)
こんな感じです

**Comment by Hukino** [comment]
![image](https://user-images.githubusercontent.com/79348353/172042937-ca7da316-d5bb-4959-8943-db14a1a1702c.png)
修正しました

**Comment by Hukino** [comment]
できた
