### ISSUE TITLE
追加［魔法］：クアラ・ステラ

### ISSUE THREAD

**Issue by zinn6118** [SALUNAinMC/SkyTraveller-datapack#59]
### 概要
- 当たり判定が幅1縦(未定)のビームを前方に射出する
- 見た目は黒を基調としたカンテラ

### 性能
- クールダウン 45sec
- 消費MP 50
-  ダメージ 未定

### タスク
- [x] 魔法のアイテムテクスチャを追加
- [x] アイテムの表示・情報を作成
- [x] 本効果を作成

**Comment by zinn6118** [comment]
やるかも

**Comment by zinn6118** [comment]
[cantera_stella.zip](https://github.com/SALUNAinMC/SkyTraveller-datapack/files/8754549/cantera_stella.zip)
![image](https://user-images.githubusercontent.com/69614928/169821487-1171fbd2-0313-4b58-ab14-a9b7d1c80984.png)

**Comment by Hukino** [comment]
できた
