### ISSUE TITLE
追加［魔法］：チェック・メイト

### ISSUE THREAD

**Issue by zinn6118** [SALUNAinMC/SkyTraveller-datapack#67]
### 概要
- 見た目はチェス盤
- ランダムなチェスの駒を召喚、その駒の進める方向にダメージを与える

### 性能
- クールダウン 3sec
- 消費MP 10
-  ダメージ 未定

### タスク
- [x] 魔法のアイテムテクスチャを追加
- [x] チェスの駒のモデルを作成
- [x] アイテムの表示・情報を作成
- [x] 本効果を作成

**Comment by zinn6118** [comment]
チェス盤だと難しそうなので見た目をチェスの駒に変更することも考えておいた方が良さそうですね

**Comment by Kiryu-for-Kiryu** [comment]
テクスチャを作成します

**Comment by Hukino** [comment]
了解です

**Comment by Kiryu-for-Kiryu** [comment]
![CheckMate](https://user-images.githubusercontent.com/95564353/156557681-566643ac-7a33-4c47-bb40-83002e083f00.png)

**Comment by Hukino** [comment]
了解しました～
PullRequest建てて頂けると幸いです

**Comment by Kiryu-for-Kiryu** [comment]
こっちに提出する前からpulllrequest立てていい感じですかね？

**Comment by Kiryu-for-Kiryu** [comment]
#78

**Comment by Kiryu-for-Kiryu** [comment]
まってなんかミスった

**Comment by Hukino** [comment]
チェスの駒のモデルを作成してくれる方を募集しています

**Comment by Hukino** [comment]
募集してません。作りました
